package main

import (
	"github.com/labstack/echo"
)
import "./routes"
import _ "./docs" // docs is generated by Swag CLI, you have to import it.


// @title Swagger Example API
// @version 1.0
// @description This is a sample Rest Api.

// @contact.name Api Support
// @x-extension-openapi {"example": "value on a json format"}
func main()  {


	e := echo.New()
	routes.RegisterRoutes(e)

	e.Logger.Fatal(e.Start(":8080"))
}
