package main

import (
	"./database"
	"./helpers/service-manager"
	"github.com/joho/godotenv"
	"github.com/labstack/echo"
	"github.com/labstack/gommon/log"
)
import "./routes"
import _ "./docs" // docs is generated by Swag CLI, you have to import it.

// @title Swagger Example API
// @version 1.0
// @description This is a sample Rest Api.
// @contact.name Api Support
// @x-extension-openapi {"example": "value on a json format"}
func main() {
	err := godotenv.Load(".env")

	if err != nil {
		log.Fatal("Error loading .env file")
	}

	db := dbconnect.SetDBConnection()
	serviceManager := servicemanager.NewServiceManager(db)
	e := echo.New()
	routes.RegisterRoutes(e, serviceManager)
	e.Logger.Fatal(e.Start(":8080"))
}
